name: Android Github Action

on:
  pull_request
    
jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: sudo ./gradlew build
        
      - name: Run Tests
        run: sudo ./gradlew test
        
      - name: Build Project
        run: sudo ./gradlew assemble
        
      - name: Build debug APK
        run: sudo ./gradlew assembleDebug --stacktrace
      
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
